### PR TITLE
Implement LoadVersion and ResetToLatest

### PR DESCRIPTION
**Pull request by cloudhead**

### CODE REVIEW

**Comment by ethanfrey** [comment]
Looks good.
But what happens when LoadVersion(v) gets a version that is not stored in the db?
It should detect this and return an error

**Comment by cloudhead** [comment]
@ethanfrey https://github.com/tendermint/iavl/pull/15/files#diff-06e77bf1f34b6f5d0fe30e83bf1f7861R88 isn't enough?

**Comment by ethanfrey** [comment]
Yes, you are right, didn't see that... prefer to review code in my editor

**Comment by ethanfrey** [comment]
then imo you can merge to sdk2

**Pull request merged**
