### PR TITLE
Use new tmlibs error

### PR DESCRIPTION
**Pull request by ebuchman**
rebased https://github.com/tendermint/iavl/pull/45

### CODE REVIEW

**Comment by ebuchman** [comment]
This has been rebased but is broken because NewErrorWithCause doesn't exist, and maybe more . Will leave for @jaekwon to correct

**Comment by ebuchman** [comment]
Also this should take into account: https://github.com/tendermint/iavl/issues/46

Repositories are always easier to maintain when there are fewer deps ...

**Comment by jaekwon** [comment]
> Repositories are always easier to maintain when there are fewer deps ...

We should move Errors out to its own repo, otherwise it's not a useful errors package for the greater go ecosystem.  It's more useful when more people are using it, and that's more likely to happen if it's a standalone repo as is pkg/errors.

**Comment by jaekwon** [comment]
https://github.com/tendermint/iavl/pull/66

**Pull request closed without merging**
