### PR TITLE
WIP: Introduce Pruning to IAVL

### PR DESCRIPTION
**Pull request by AdityaSripal**
Introduces notion of pruning to IAVL. `MutableTree` has `keepRecent` and `keepEvery` fields. Recent versions get saved in memDB while snapshot versions get saved to levelDB. For more details see:
https://github.com/tendermint/iavl/issues/144#issuecomment-509774282

Based off Loom PR (#150).

### CODE REVIEW

**Comment by AdityaSripal** [comment]
TODO: Move all pruning logic out of mutableTree and into nodedb

**Comment by marbar3778** [comment]
Had to change base branch to develop as we haven't nuked develop yet on this repo. Once we get this done, then will move base back to master

**Comment by AdityaSripal** [comment]
TODO:

- Write up doc explaining design choices and expected behaviour
- Lots more testing on nodeDB functionality, pruning tests in general (nodeDB, mutable_tree)
- Benchmarks for various pruning strategy (Default: {keepEvery: 1, keepRecent: 0}, NoSnapshot: {keepEvery: 0, keepRecent: 100}, Snapshotting: {keepEvery: 10000, keepRecent: 100}, RandomPruning)

**Comment by AdityaSripal** [comment]
Closing to create in-org branch

**Pull request closed without merging**
